### ISSUE TITLE
Assignment bugs and String handling

### ISSUE THREAD

**Issue by rocky** [skuznetsov/depyo.js#1]
Consider this program, shortened from [uncompyle6/est/simple_source/stmts/01_augmented_assign.py](https://github.com/rocky/python-uncompyle6/blob/master/test/simple_source/stmts/01_augmented_assign.py): 

```python
raise RuntimeError("This program can't be run")
x = [1,2,3]
x[:] += [9];
x[1:] += [9];
x[1:4] += [9];

i = j = k = 1
def f():
    global i
    i += 1
    return i

x[f()][j][k] += 1
```

When compiled and decompiled I see this: 

```python
raise RuntimeError('This program can't be run')
x = [1, 2, 3]
x[:] = x[:] + [9]
1[x:]
4[1:x]
j = i=1
k = 1

def 1[x:1[x:] + [9]] + [9]():
    i=i + 1
    return i
k[x[f()][j]] = 1[x:1[x:] + [9]] + [9][1[x:] + [9]] + 1
```

This shows a number of problems in decompilation: 

* The single quote of "can't" needs to be escaped or different outer quotes need to be used.
* Slicing parameters get jumbled around and an assignment is lost: `x[1:4] = 9` becomes `4[1:x]`
* the inline assignment on the last line is both weirdly wrong, but also messes up the function name of the `def` 
* the "global" statement inside the "def" is missing

In the not wrong, but weird category,  `i += 1`  becomes `i=i + 1`  and `i = j = k = 1` becomes two statements: `j = i=1` and `k = 1`

**Comment by skuznetsov** [comment]
Hi @rocky,

Thank you very much for filing this issue!
I will look into it!

In case of:
   `i += 1`
vs:
   `i = i + 1`

I have to look at bytecode of the method.

For **+=** situations Python compiler should inject **INPLACE_ADD** bytecode.

I believe that most of these issues will be solved when I refactor the decompiler code to use AST; in that case, I can reuse Line Tamle information for the method to do the proper aggregation, closer to the original.

**Comment by rocky** [comment]
+1 for refactoring to work off an AST. In general, as with compilers the more one can separate decompilation into _phases_ the better the code organization and comprehensibility will be. 

If there is not a command-line option to dump information at each of the phases, I'd suggest adding one.

I have tried using at Line Table information, and while that is intriguing and  might suggest things, I have found you can't really rely too much on it.  One can write use semicolons to join lines.

**Comment by skuznetsov** [comment]
Hey, @rocky!

I am not lost.
I am refactoring the code to support all Python versions and AST support (I am reusing some of the data from the PYCDC code, but I promise to donate my time back to that project, and I already made code changes to pycdc that I plan to commit soon).

I wanted to ask you if you are fine with me reusing your test Python bytecode samples.

**Comment by rocky** [comment]
Feel free to use the Python bytecode samples!

**Comment by skuznetsov** [comment]
Hey, @rocky!

I refactored the code. It is still stabilizing, but most of the code is working correctly. 
At least it recovers your example from this issue correctly.

```
raise RuntimeError('This program can't be run')
x = [1, 2, 3]
x[:] += [9]
x[1:] += [9]
x[1:4] += [9]
i = j = k = 1
def f():
    global i
    i += 1
    return i

x[f()][j][k] += 1
x[f()] += 1

```
I merged the changes to the master branch.

I still have to fix the bug with changing the quotes if a single quote is present in the string.

Please let me know what you think about it.

**Comment by rocky** [comment]
As best as I can tell, reorganizing along bytecode versions is good and it is good you support up to Python 3.12. 

The specific changes are too massive for me to follow. 

<strike>Perhaps if you add a wiki entry or something like that I could comment and hopefully it would make it easier for others to follow the code.</strike>

I forgot about your medium post. It would help forgetful people like me to put a link in this project to that in a top-level README.

**Comment by rocky** [comment]
A  README with how to run this would be nice. I tried :

```
$ node --version
v12.18.3

$ node ./app.js
/tmp/depyo.js/lib/OpCodes.js:711
            if (this.DOMINATORS.includes(dominatorOp?.OpCodeID)) {
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/depyo.js/lib/bytecode/python_1_0.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
$    
```

**Comment by skuznetsov** [comment]
This is still the Alpha version that I want to stabilize.
I will provide the documentation as well ah CLI help output.

 My bad! I used the last JavaScript feature that was added somewhere around NodeJS version 14. I should modify the syntax back to the explicit if condition so it can be used in the earlier version of NodeJS.
 
 It may be a great idea to convert this code to Python then, so that you can use any Python from version 2.7 and up.

**Comment by rocky** [comment]
There would be a lot of work needed in JS to get it to support 2.7 to 3.8 as well as uncompyle6 and decompyle3 do. 

Personally, I think there is a lot more needed in terms of thinking about how to cover in scalable way the vast number constructs involving control flow including exception handling, that will be needed, just for 3.9 to 3.12 and beyond. 

People underestimate the amount of work needed, and most projects just don't have the infrastructure to do proper testing. (Are there _any_ automated tests for this code?) 

I would doubt this code as it is handles more than 80% of tests in the existing test suite and that still is lacking in terms of coverage.

**Comment by skuznetsov** [comment]
It is not stable yet, but it can solve some optimized bytecode cases in a private project with thousands of files, where it replaces JUMP_FORWARD with JUMP_ABSOLUTE backward, and the code that you saw in the stacktrace, is resolving it to the proper offset to identify the block it belongs to.

Thank you for the test cases! I will run them to see what is the pass rate.

**Comment by skuznetsov** [comment]
@rocky 
In the latest version, I was able to distinguish between:
```
try:
  a = 1
except:
  a = 2
finally:
  a = 3
```
and

```
try:
  try:
    a = 1
  except:
    a = 2
finally:
  a = 3
```
they look exactly the same on the byte code level, but line info data is different for SETUP_FINALIZE and SETUP_EXCEPT.

So, in my tests, it is correctly identifying both cases.
